import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider, Header } from "./components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex flex-col w-full h-screen'>
          <AuthProvider>
            <Header />
            <div className='flex justify-center overflow-y-auto px-2 py-2'>
              <div className="flex flex-col gap-2 w-full md:w-[768px] lg:w-[1024px] justify-start">
                {children}
              </div>
            </div>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
